# Generated by Django 3.1.6 on 2021-03-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='page',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
