# Generated by Django 3.1.6 on 2021-02-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lenguaje',
            field=models.CharField(default='C#', max_length=100),
        ),
    ]
