# Generated by Django 3.1.6 on 2021-02-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0002_project_lenguaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lenguaje',
            field=models.CharField(max_length=100),
        ),
    ]
