# Generated by Django 3.1.6 on 2021-02-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0003_auto_20210224_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
