# Generated by Django 3.1.6 on 2021-02-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0004_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
